version: '3.8'

services:

  mysql-dbms:
    image: mysql
    container_name: mysql-dbms
    ports:
      - 3306:3306
    volumes:
      - mysql-dbms-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-app-root-password-12345
      MYSQL_USER: tanmayvaij
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: strapi-cms-db

  strapi-cms:
    image: strapi/strapi
    container_name: strapi-cms
    ports:
      - 1337:1337
    volumes:
      - strapi-cms:/app
      - strapi-cms/public/uploads:/app/public/uploads
    depends_on:
      - mysql-dbms
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql-dbms
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi-cms-db
      DATABASE_USERNAME: tanmayvaij
      DATABASE_PASSWORD: 12345678
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: "89uw5g9w20g9205,095w2g90j20j909j2"
      API_TOKEN_SALT: w09u5g0wg9jgsngekonognwsngo
      ADMIN_JWT_SECRET: tobeosijrgjw0ew90jvrmodified
      TRANSFER_TOKEN_SALT: e20910498qwjh9g0sjtoinxzsb9tiw
      JWT_SECRET: tj0w9jg0j9e4ojgosgzse90a9w30j39r
      NODE_ENV: production

volumes:
  mysql-dbms-data:

networks:
  default:
    name: strapi-mysql-network
